# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Wiloti"
weight = 1


[fr]
languageName = "Français"
languagedirection = "ltr"
title = "Wiloti"
weight = 2
