# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/wiloti"

[social.params]
icon = "brand-github"

[[social]]
identifier = "hackthebox"
name = "Hack The Box"
url = "https://app.hackthebox.com/users/618895"

[social.params]
icon = "cube"

[[social]]
identifier = "rootme"
name = "Root Me"
url = "https://www.root-me.org/Wiloti?lang=en"

[social.params]
icon = "skull"
